'use strict';
// console.log("hello");
// console.log('hello'.toUpperCase());
// console.log('hello'.length);
// let userName = 'Aniya';
// console.log(typeof userName);
// alert(userName);
// const value = prompt('Please enter your name!');
// console.log(value);
// const isComing = confirm('Please confirm hotel reservation');
// console.log(isComing);
// const x = 9;
// const y = 5;
// console.log(x % y);
// let z = 5;
// z += 10;
// console.log(z);
// console.log(1 !== 2);
// console.log(2 === 3);
console.log(Number('3'));
console.log(Number('v'));
console.log(Number.parseInt('12.46px'));
console.log(Number.parseFloat('12.46px'));
let invalidNumber = Number('ghvhgg');
console.log(Number.isNaN(invalidNumber));
invalidNumber = 5;
console.log(Number.isNaN(invalidNumber));
console.log((0.17 + 0.24).toFixed(2));
console.log(Math.floor(1.7));
console.log(Math.ceil(1.7));
console.log(Math.round(1.7));
console.log(Math.max(32.1, 10, 32, 1));
console.log(Math.pow(3, 2));
console.log(Math.random());
console.log(Math.random() * (10 - 1) + 1);
let message = 'Mango' + ' is' + ' a' + ' fruit';
console.log(message);
message = 1 + '3';
console.log(message, typeof message);
let guestName = 'Mango';
let roomNumber = 207;
let greeting = `Welcome ${guestName}, your room number is ${roomNumber} `;
console.log(greeting);
guestName = 'Apple';
roomNumber = 13;
greeting = `Welcome ${guestName}, your room number is ${roomNumber} `;
console.log(guestName, roomNumber, greeting);
console.log(greeting.length, greeting.toUpperCase(), greeting.toLowerCase());
console.log(greeting.indexOf('13'));
console.log(greeting.includes('13'));
console.log(greeting.endsWith(' '));
console.log(greeting.replaceAll('13', '222'));
console.log(greeting.slice(0, 35)); 



